sudo: false

language: python
python:
  - '3.6'

services:
  docker

before_script:

script:
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml up

after_script:
  - docker-compose down
