version: '3'

services:

  server:
    image: python:3.6
    working_dir: /mnt
    volumes:
      - .:/mnt
    links:
     - db
    depends_on:
      - db
    ports:
      - '5000:5000'
    env_file: ./.env
    environment:
      PYTHONPATH: $PYTHONPATH:src
      PYTHONUSERBASE: /mnt/vendor
      IMPORT_PATH: /mnt/test/fixture
    command: python src/server.py

  db:
    image: postgres
    env_file: ./.env
    volumes:
      - /var/lib/postgresql/data
